services:
   easynode:
      build: .
      container_name: easynode
      image: mobufan/easynode:latest
      restart: always
      ports:
         - 8082:8082
      volumes:
         - ./easynode/db:/easynode/app/db
         - /var/run/docker.sock:/var/run/docker.sock:ro
      environment:
         - GUACD_PORT=4822
         - GUACD_HOST=127.0.0.1