services:
   fan-webssh:
      build: .
      container_name: fan-webssh
      image: mobufan/fan-webssh:latest
      restart: always
      ports:
         - 8082:8082
      volumes:
         - ./fan-webssh/db:/fan-webssh/app/db
         - /var/run/docker.sock:/var/run/docker.sock:ro
      environment:
         - GUACD_PORT=4822
         - GUACD_HOST=guacd
      depends_on:
         - guacd

   guacd:
      container_name: guacd
      image: guacamole/guacd:latest
      restart: always
      ports:
         - 4822:4822